### ISSUE TITLE
Links redirecting to old website

### ISSUE THREAD

**Issue by rktejesh** [eCell-IIITL/Ecell_Website#30]
Teams page link on enspire website page redirects to old website. Check all links on the website are redirected to ecell.iiitl.ac.in domain.

Make a list of all non working links and add in the comments.

Mention all the changes done in the PR desc.

**Comment by rktejesh** [comment]
Go ahead👍

**Comment by palashb01** [comment]
under the Teams section on home website :
links not working:
1) Our works
2) Our Events
3) Our sponsors

-> The links are not redirecting to any page

**Comment by palashb01** [comment]
under the team option in sidebar:
the teams button redirects to the old website.

i am changing the href in the team option to the new page.

**Comment by rktejesh** [comment]
Update the link for our events also - there is a ./events.html. Also update the navbar on this page
